# Generated by Django 4.2 on 2025-09-15 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_event_please_check_the_event_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='please check the event date',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gt', datetime.datetime(2025, 9, 15, 14, 59, 45, 784382))), name='please check the event date'),
        ),
    ]
